pluralize function for common/string
tgstation/tgui-core pull request #3
Opened 2024-07-23 07:09 UTC by ZeWaka

title, should be useful
currently we use `export const pluralize = (word: string, n: number) => (n !== 1 ? word + 's' : word);` which is nice but this should Work For Everything now

thought `VOWELS` might be useful for consumers

2024-07-23 09:33 UTC, ZephyrTFA requested changes
export a function instead of an anonymous function

2024-07-28 06:19 UTC, ZeWaka reviewed
unsure if you want the compiled `dist/` files committed in the PR or not

2024-07-28 09:51 UTC, ZephyrTFA commented
probably not, will discuss in future with shadow

2024-07-28 09:51 UTC, ZephyrTFA approved these changes

2024-07-28 09:51 UTC, merged